import {
  AlertTriangle,
  ArrowDownToLine,
  ArrowUpFromLine,
  Box,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  FileText,
  LayoutDashboard,
  LogOut,
  Menu,
  MoreVertical,
  Package,
  PackageCheck,
  PackageOpen,
  Pencil,
  PieChart,
  Plus,
  Printer,
  Receipt,
  RotateCcw,
  Search,
  Settings,
  ShoppingCart,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  X,
  RefreshCw,
  PhoneCall,
  Mail,
  Building,
  MapPin,
  Barcode,
  Share2,
  Sun,
  Moon,
  Bell,
  SlidersHorizontal,
  Command,
  HelpCircle,
  FolderTree,
  Scale,
  History,
  Calendar,
  ShieldAlert,
  ShieldCheck,
  FileSpreadsheet,
  Download,
  ExternalLink,
  Activity,
  DollarSign,
  Layers
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  inventory: Box,
  products: Package,
  sales: ShoppingCart,
  purchase: Receipt,
  receipts: PackageOpen,
  payments: CreditCard,
  customers: Users,
  suppliers: Building,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  close: X,
  add: Plus,
  back: ChevronLeft,
  forward: ChevronRight,
  more: MoreVertical,
  search: Search,
  print: Printer,
  share: Share2,
  trash: Trash2,
  refresh: RefreshCw,
  edit: Pencil,
  save: PackageCheck,
  eye: Search,
  purchaseOrders: Receipt,
  invoice: FileText,

  // Status icons
  check: Check,
  success: CheckCircle2,
  warning: AlertTriangle,
  info: FileText,

  // Movements
  in: ArrowDownToLine,
  out: ArrowUpFromLine,

  // Custom context
  delivery: Truck,
  delivered: PackageCheck,
  phone: PhoneCall,
  email: Mail,
  location: MapPin,
  barcode: Barcode,
  document: ClipboardList,
  chart: PieChart,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  undo: RotateCcw,
  returns: RotateCcw,
  supplierReturns: ArrowUpFromLine,
  clock: Clock,
  sun: Sun,
  moon: Moon,
  bell: Bell,
  command: Command,
  filter: SlidersHorizontal,
  help: HelpCircle,
  categories: FolderTree,
  stockAdjustments: Scale,
  scale: Scale,
  history: History,
  timeline: History,
  calendar: Calendar,
  aging: Calendar,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  spreadsheet: FileSpreadsheet,
  download: Download,
  external: ExternalLink,
  activity: Activity,
  dollar: DollarSign,
  layers: Layers,
};
